# Presenting Models using Bookdown  {#presentwithBookdown}
Recently there has been a lot of development with respect to using R Shiny apps to present stock assessment models to technical working groups. A problem with Shiny is it requires you to host the app somewhere which can encounter permission and confidentiality issues. An approach that I believe is worth exploring is using the R package `library(bookdown)`. This package allows users to bundle results into an html book that can be accessed locally by opening the html files within a web browser. This would allow it for easy distribution of  HTML files to the necessary parties/stakeholders, in addition to it being easily archived by administrators (which is difficult with shiny apps).


Often when presenting Casal2 models we present a suite of models. This means each presentation will be bespoke to the problem as you may want to emphasis different model characteristics. That being said, this chapter will walk through an example that I have recently been working on, with the aim of providing a template for others to use. 

The main function that has been created for this task is `?build_assessment_bookdown`.





